### ISSUE TITLE
looking forward the code

### ISSUE THREAD

**Issue by cuge1995** [Vandermode/TFPnP#1]

**Comment by xiaoiker** [comment]
+1

**Comment by tianweiy** [comment]
++1 A code release will greatly increase your paper's popularity and potential impact.

**Comment by Vandermode** [comment]
Hi, according to some discussions of my co-authors, the code release might be slightly delayed, but will be released definitely

**Comment by tianweiy** [comment]
@Vandermode  Can you share a link to your supplementary materials? ( as it has been mentioned several times that certain details are in it) I really appreciate this

**Comment by Vandermode** [comment]
Sure, here is the [link](https://proceedings.icml.cc/static/paper_files/icml/2020/4134-Supplemental.pdf)

**Comment by tianweiy** [comment]
Cool, thanks!
