### ISSUE TITLE
如果将最大时间步设置为1效果会怎么样？

### ISSUE THREAD

**Issue by lixyxd** [Vandermode/TFPnP#4]
如题，我在实验中发现最大时间步为1效果好像更好

**Comment by Vandermode** [comment]
Could you let me know the hyperparameter setting you used? max_episode_step=1 and what's the "action_pack"?

**Comment by lixyxd** [comment]
非常感谢您的回复，我在想，如果最大时间步设置为1，action_pack设置为15或者20等等，不考虑算法自动停止，是否可以看作是单步强化学习，直接寻找从初始状态到最终结果的最优动作。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Kaixuan ***@***.***>
发送时间: 2022年10月8日 10:14
收件人: ***@***.***>
抄送: ***@***.***>; State ***@***.***>
主题: Re: [Vandermode/TFPnP] 如果将最大时间步设置为1效果会怎么样？ (Issue #4)


Could you let me know the hyperparameter setting you used? max_episode_step=1 and what's the "action_pack"?

―

**Comment by Vandermode** [comment]
Yes, in this case, reinforcement learning might not be necessary. The algorithm would become a kind of deep unrolling architecture with fixed iterations

**Comment by lixyxd** [comment]
是的，感谢您的答复！

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
