### ISSUE TITLE
How to calculate SSIM

### ISSUE THREAD

**Issue by syf0518** [Vandermode/TFPnP#6]
Thanks for your contribution, it is wonderful.I wanted to use your code as a comparison algorithm for CT reconstruction, but I found that only PSNR but no SSIM was calculated in the code.I see PSNR is calculated by "eval_psnr = self.evaluator.eval(self.actor, step)", but I don't know how to calculate SSIM by using "self.actor" and "step".I would appreciate it if you could tell me.

**Comment by Vandermode** [comment]
Hey, thanks for your interest. If you just care about the evaluation. Perhaps you just simply save the results and compare the SSIM offline.

**Comment by syf0518** [comment]
> Hey, thanks for your interest. If you just care about the evaluation. Perhaps you just simply save the results and compare the SSIM offline.

That's a good idea, thank you for your reply.I have another question.I want to calculate the number of parameters for the TFPnP, so I wrote a function:
![图片](https://github.com/Vandermode/TFPnP/assets/104410659/07988b85-6e45-4372-8692-6ad3585170d3)
Can I use it by "print_network(trainer)" in main.py?I would appreciate it if you could tell me.
