### ISSUE TITLE
How to calculate the number of parameters in the network

### ISSUE THREAD

**Issue by syf0518** [Vandermode/TFPnP#7]
Thanks for your contribution, it is wonderful.I wanted to use your code as a comparison algorithm for CT reconstruction, so I want to calculate the number of parameters in TFPnP.I tried to calculate it by trainer.parameters() but failed.So I want to know calculate the number of parameters in TFPnP.I would appreciate it if you could tell me.

**Comment by Vandermode** [comment]
Hello, TFPnP consists of two networks at inference, one is the denoising network used as prior, another is the policy network for scheduling the optimization parameters. So finding the UNet (denoiser) and the ResNet (policy network) in the codebase, and summing their parameters together should serve your purpose

**Comment by syf0518** [comment]
Thank you for your reply.I calculated the number of parameters of UNet and ResNet respectively, and the total number of parameters was 22.95M.
